"""gRPC services for Envoy ext_authz / ext_proc filters + operational admin.

See :mod:`portunus.grpc.server` for lifecycle. Gated on
:attr:`portunus.config.GrpcConfig.enabled` (default off).

Generated protobuf stubs live under :mod:`portunus.admin` (regenerated by
``scripts/gen_proto.sh``). They are ordinary submodules of the ``portunus``
package, so they import each other by absolute import with no ``sys.path``
manipulation.
"""

from portunus.grpc.auth_servicer import PortunusAuthServicer
from portunus.grpc.proc_servicer import PortunusProcessServicer

__all__ = ["PortunusAuthServicer", "PortunusProcessServicer"]
