"""gRPC services for Envoy ext_authz / ext_proc filters + operational admin.

See :mod:`portunus.grpc.server` for lifecycle. Gated on
:attr:`portunus.config.GrpcConfig.enabled` (default off).

Buf-generated protobuf stubs live under ``_generated/`` (regenerated by
``buf generate``; see ``buf.gen.yaml``). They import each other by their proto
package root (``portunus_admin.v1``), so ``_generated`` must be importable. We
prepend it to ``sys.path`` here rather than rewriting the generated imports,
keeping the generated tree byte-identical to ``buf generate`` output (which the
pre-commit / CI freshness check asserts). ``_generated`` ships inside this
package, so the same path works for the installed wheel.
"""

import os
import sys

_GENERATED = os.path.join(os.path.dirname(__file__), "_generated")
if _GENERATED not in sys.path:
    sys.path.insert(0, _GENERATED)

# E402: these must follow the sys.path insert above so the generated stubs
# (which servicers import transitively) resolve.
from portunus.grpc.auth_servicer import PortunusAuthServicer  # noqa: E402
from portunus.grpc.proc_servicer import PortunusProcessServicer  # noqa: E402

__all__ = ["PortunusAuthServicer", "PortunusProcessServicer"]
