# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from portunus.admin.v1 import admin_pb2 as portunus_dot_admin_dot_v1_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in portunus/admin/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """AdminService exposes operational actions that previously lived on the
    retired FastAPI REST surface (`POST /cache/flush`).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FlushCache = channel.unary_unary(
                '/portunus.admin.v1.AdminService/FlushCache',
                request_serializer=portunus_dot_admin_dot_v1_dot_admin__pb2.FlushCacheRequest.SerializeToString,
                response_deserializer=portunus_dot_admin_dot_v1_dot_admin__pb2.FlushCacheResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """AdminService exposes operational actions that previously lived on the
    retired FastAPI REST surface (`POST /cache/flush`).
    """

    def FlushCache(self, request, context):
        """FlushCache clears the entire Redis auth cache, forcing every subsequent
        request to re-authenticate against AWS. Use after a cached upstream key
        may have been compromised. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FlushCache': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushCache,
                    request_deserializer=portunus_dot_admin_dot_v1_dot_admin__pb2.FlushCacheRequest.FromString,
                    response_serializer=portunus_dot_admin_dot_v1_dot_admin__pb2.FlushCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'portunus.admin.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('portunus.admin.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """AdminService exposes operational actions that previously lived on the
    retired FastAPI REST surface (`POST /cache/flush`).
    """

    @staticmethod
    def FlushCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/portunus.admin.v1.AdminService/FlushCache',
            portunus_dot_admin_dot_v1_dot_admin__pb2.FlushCacheRequest.SerializeToString,
            portunus_dot_admin_dot_v1_dot_admin__pb2.FlushCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
