#!/usr/bin/env python3
"""
Generate test data by making HTTP requests through the proxy.

This script sends requests through the Portunus proxy, which will:
1. Authenticate via the /authorise endpoint
2. Forward requests to the target (http-bin)
3. Log request/response data to Kinesis
4. Flow through Firehose to S3 for Glue processing

This tests the entire pipeline end-to-end with varied HTTP scenarios.
"""

import time
from typing import Tuple

import requests

# Proxy configuration
PROXY_URL = "http://localhost:8888"

# Test scenarios using different httpbun endpoints
TEST_SCENARIOS = [
    {
        "name": "POST with JSON body",
        "method": "POST",
        "path": "/post",
        "headers": {"Content-Type": "application/json"},
        "body": {"model": "gpt-4", "prompt": "Hello, world!", "max_tokens": 100},
    },
    {
        "name": "GET with query parameters",
        "method": "GET",
        "path": "/get?param1=value1&param2=value2",
        "headers": {},
        "body": None,
    },
    {
        "name": "POST with form data",
        "method": "POST",
        "path": "/post",
        "headers": {"Content-Type": "application/x-www-form-urlencoded"},
        "form_data": {"field1": "value1", "field2": "value2"},
    },
    {
        "name": "Request with custom headers",
        "method": "GET",
        "path": "/headers",
        "headers": {
            "X-Custom-Header": "custom-value",
            "X-Request-ID": "test-123",
            "Accept": "application/json",
        },
        "body": None,
    },
    {
        "name": "Status code test (200)",
        "method": "GET",
        "path": "/status/200",
        "headers": {},
        "body": None,
    },
    {
        "name": "Status code test (404)",
        "method": "GET",
        "path": "/status/404",
        "headers": {},
        "body": None,
    },
    {
        "name": "Status code test (500)",
        "method": "GET",
        "path": "/status/500",
        "headers": {},
        "body": None,
    },
    {
        "name": "PUT request with JSON",
        "method": "PUT",
        "path": "/put",
        "headers": {"Content-Type": "application/json"},
        "body": {"action": "update", "resource_id": 12345},
    },
    {
        "name": "DELETE request",
        "method": "DELETE",
        "path": "/delete",
        "headers": {},
        "body": None,
    },
    {
        "name": "Large JSON payload",
        "method": "POST",
        "path": "/post",
        "headers": {"Content-Type": "application/json"},
        "body": {
            "model": "claude-3-opus",
            "messages": [
                {"role": "user", "content": "Tell me a story about " + "x" * 500}
            ],
            "max_tokens": 4096,
            "temperature": 0.7,
        },
    },
]


def create_mock_authorization_header() -> str:
    """
    Create a mock authorization header for testing.

    In production, this would be generated by api_key_override() from util.py,
    but for local testing we just use the "xyz" configured in localstack.
    """
    return (
        "Bearer eyJjcmVkZW50aWFscyI6eyJhY2Nlc3Nfa2V5X2lkIjoiQUtJQVRFU1QiLCJ"
        "zZWNyZXRfYWNjZXNzX2tleSI6IlNFQ1JFVFRFU1QiLCJzZXNzaW9uX3Rva2VuIjoiVE"
        "VTVFRPS0VOIn0sInNlY3JldF9hcm4iOiJhcm46YXdzOnNlY3JldHNtYW5hZ2VyOnVzL"
        "WVhc3QtMToxMjM0NTY3ODkwMTI6c2VjcmV0OnRlc3Qtc2VjcmV0In0="
    )


def make_test_request(scenario: dict, request_num: int) -> Tuple[bool, int]:
    """
    Make a test request through the proxy using the given scenario.

    Returns:
        Tuple of (success: bool, status_code: int)
    """
    # Build headers with authorization
    headers = {
        "Authorization": create_mock_authorization_header(),
        "User-Agent": f"test-client/1.0 (request-{request_num})",
    }
    headers.update(scenario.get("headers", {}))

    method = scenario["method"]
    path = scenario["path"]
    url = f"{PROXY_URL}{path}"

    try:
        print(f"  {method} {path}")

        # Make the request using the appropriate method
        # Add body/data based on scenario
        if "form_data" in scenario:
            response = requests.request(
                method, url, headers=headers, data=scenario["form_data"], timeout=30
            )
        elif scenario.get("body") is not None:
            response = requests.request(
                method, url, headers=headers, json=scenario["body"], timeout=30
            )
        else:
            response = requests.request(method, url, headers=headers, timeout=30)

        print(f"  Response status: {response.status_code}")

        # Consider any response a success (even 4xx/5xx are valid test cases)
        return (True, response.status_code)

    except Exception as e:
        print(f"  Request failed: {e}")
        return (False, 0)


def main():
    """Generate test data by making requests through the proxy."""
    print("=" * 70)
    print("Generating test data via proxy requests")
    print("=" * 70)
    print()

    # Verify proxy is accessible
    try:
        requests.get(f"{PROXY_URL}/", timeout=5)
        print(f"✓ Proxy accessible at {PROXY_URL}")
    except Exception as e:
        print(f"✗ Cannot reach proxy at {PROXY_URL}: {e}")
        print("\nPlease ensure docker-compose stack is running:")
        print("  docker compose up -d")
        return 1

    print()
    print(f"Making {len(TEST_SCENARIOS)} varied test requests through the proxy...")
    print("This will populate Kinesis → Firehose → S3 with diverse data")
    print()

    successful_requests = 0
    status_code_summary = {}

    for i, scenario in enumerate(TEST_SCENARIOS, 1):
        print(f"Request {i}/{len(TEST_SCENARIOS)}: {scenario['name']}")
        success, status_code = make_test_request(scenario, i)

        if success:
            successful_requests += 1
            status_code_summary[status_code] = (
                status_code_summary.get(status_code, 0) + 1
            )
            print("  ✓ Success")
        else:
            print("  ✗ Failed")

        # Small delay between requests
        if i < len(TEST_SCENARIOS):
            time.sleep(0.5)

        print()

    print("=" * 70)
    print("Test data generation complete!")
    print(f"Successful requests: {successful_requests}/{len(TEST_SCENARIOS)}")
    print()
    print("Response status codes:")
    for status_code in sorted(status_code_summary.keys()):
        count = status_code_summary[status_code]
        print(f"  {status_code}: {count} request(s)")
    print()
    print("Next steps:")
    print("  1. Wait 15-30 seconds for Firehose to flush data to S3")
    print("  2. Verify data in S3:")
    print(
        "     docker exec localstack-main awslocal s3 ls "
        "s3://portunus-logs-local/logs/ --recursive"
    )
    print("  3. Run the Glue job:")
    print("     ./scripts/run-glue-job.sh")
    print("  4. Extract and inspect results:")
    print("     python3 scripts/extract-glue-output.py")
    print("=" * 70)

    return 0 if successful_requests == len(TEST_SCENARIOS) else 1


if __name__ == "__main__":
    exit(main())
