name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit
  format:
    uses: ./.github/workflows/format.yml
    secrets: inherit
  type-check:
    uses: ./.github/workflows/type-check.yml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
