name: Test Lua Library

on:
  workflow_call:

jobs:
  lua-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Lua test image
        run: |
          cd proxy/lib
          docker build -f Dockerfile.test -t proxy-utils-tests .

      - name: Run Lua tests
        run: |
          docker run --rm proxy-utils-tests
